### ISSUE TITLE
Exceptions fetching settings using MBOptionScreen v2.0.8

### ISSUE THREAD

**Issue by Katarn2000x** [Aragas/Bannerlord.MBOptionScreen#13]
I'm getting some bug reports from users of my mod of crashing when fetching settings:
https://imgur.com/MrYh6Ma

It does not occur on a fresh e1.3 install with just my mod running so I suspect there is some conflict with another version of MBOptionScreen or Modlib.

SubModule XML:
https://github.com/Katarn2000x/DiplomacyFixes/blob/master/SubModule.xml

Settings:
https://github.com/Katarn2000x/DiplomacyFixes/blob/master/Settings.cs

Crash Source:
https://github.com/Katarn2000x/DiplomacyFixes/blob/master/Patches/PoliticalStagnationAndBorderIncidentCampaignBehaviorPatch.cs#L17

**Comment by Aragas** [comment]
This is an issue with the 'multiple assembly loading' approach the MCM went.
We detected too late that the game won't initialize those loaded assemblies if their ``MBSubModuleBase`` shares the same name.

The fix for this issue is to keep the ``MBSubModuleBase`` class name unique across versions, so starting from 2.0.10 its now ``MBOptionScreen.MBOptionScreenSubModuleV2010``.
SubModuleClassType in SubModule.xml should be updated accordingly to the name.

I advise to update to it!

**Comment by Katarn2000x** [comment]
Thanks. This was the problem!
