### ISSUE TITLE
Canceling setting changes not works with unallowed values

### ISSUE THREAD

**Issue by artifixer** [Aragas/Bannerlord.MBOptionScreen#162]
Steps to reproduce.
1. Edit any Integer setting manually (not with a slider but via direct value entering).
2. Set the value above or below the restriction.
3. Hit "Done".
4. The changed setting will show the appropriate cap instead of the entered value, but ignore that.
4. Exit the settings configuring screen by hitting "Cancel".
5. Re-open the mod settings - they will show the values you've entered.
6. Restarting the game fixes the issue (because the the settings file was not changed), but until then game will use the wrong values.

**Comment by Aragas** [comment]
Might be fixed by the switch to game provided edit box, need to check

**Comment by Aragas** [comment]
Investigated the issue.
The value changes 2 times when being overflown. First, the original value (i.e. 0), then the value that is over the restrictions (i.e. 200), then the rounded down value (0-100, 100) by the game.
Our do-undo system will capture 200 as the original value instead of 0 and 100 as the changed value
The do-undo system is not expecting changing the value in the middle of the whole flow, will need further investigation.

**Comment by Aragas** [comment]
Not possible anymore with the UI system, the new input box we use does not allow setting a value, plus when setting via the UI we clamp the value.

This still should be possible if we edit the value directly in the model, but we never had a mechanism for clamping the values in the model, this falls on the mod developer.
We could clamp the value when we receive a PropertyChanged event, but I don't think the UI module should enforce this behaviour
