### ISSUE TITLE
Causes game to go into infinite loading screen on Linux

### ISSUE THREAD

**Issue by TheKarion** [Aragas/Bannerlord.MBOptionScreen#267]
Tested on Proton 7.0.4, Proton GE 7.33 and Proton Experimental, might be a missing dotnet472 dependency but I can't install that via protontricks for some reason.

**Comment by TheKarion** [comment]
Hey I thought I'd try and contribute to help and I got a proton log. The game freezes as soon as you click off of the window so it didn't crash but just froze so I force closed it with steam.
[steam-261550.log](https://github.com/Aragas/Bannerlord.MBOptionScreen/files/9637700/steam-261550.log)

**Comment by Loico84** [comment]
Me too on Fedora 36.

**Comment by albin-engstrom** [comment]
I seem to have the same issue.

On Arch, and similarly tried Proton 7.0-4, GE 36 and Experimental.
I also can't install dotnet.

This error repeated twice in the console before the loading becomes seemingly infinite and nothing more seems to happen.

`Unhandled Exception:
System.TypeLoadException: Could not load type of field 'MCM.UI.Functionality.DefaultIngameMenuScreenHandler+<>c__DisplayClass11_0:__instance' (0) due to: Could not load file or assembly 'SandBox.View, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
  at (wrapper managed-to-native) System.RuntimeTypeHandle.type_is_assignable_from(System.Type,System.Type)
  at System.RuntimeTypeHandle.CanCastTo (System.RuntimeType type, System.RuntimeType target) [0x00000] in <e70d6e9587d64cb3abb4b3f99bbf5a0d>:0 
  at System.RuntimeType.IsAssignableFrom (System.Type c) [0x00020] in <e70d6e9587d64cb3abb4b3f99bbf5a0d>:0 
  at TaleWorlds.MountAndBlade.Module.CollectModuleAssemblyTypes (System.Reflection.Assembly moduleAssembly) [0x00160] in <1310db3704d74fc58555397bef6bd533>:0 
  at TaleWorlds.MountAndBlade.Module.AddSubModule (System.Reflection.Assembly subModuleAssembly, System.String name) [0x00015] in <1310db3704d74fc58555397bef6bd533>:0 
  at TaleWorlds.MountAndBlade.Module.LoadSubModules () [0x0016e] in <1310db3704d74fc58555397bef6bd533>:0 
  at TaleWorlds.MountAndBlade.Module.Initialize () [0x000c9] in <1310db3704d74fc58555397bef6bd533>:0 
  at ManagedCallbacks.CoreCallbacksGenerated.Module_Initialize (System.Int32 thisPointer) [0x00006] in <d71790610e964db5b44f485dfc09dd5e>:0 
  at (wrapper native-to-managed) ManagedCallbacks.CoreCallbacksGenerated.Module_Initialize(int)
`

**Comment by albin-engstrom** [comment]
I managed to find a workaround.

I found this older issue also discussing this same problem; https://github.com/Aragas/Bannerlord.MBOptionScreen/issues/108

It contains various solutions which worked for some.

What I in the end did was create a clean prefix with 5.0-10, run `protontricks 261550 dotnet472` which works and takes a long time, and then change back to GE 36.

**Comment by TheKarion** [comment]
Oh interesting, I'll try that out and share my results

**Comment by Loico84** [comment]
I confirm that it works correctly on Fedora 36. I removed prefix directory and I used Proton 5.0-10 (no GE version) to install dotnet472 (it took an hour) and then use proton GE 7 to play Bannerlord (e1.9.0).

**Comment by TheKarion** [comment]
Didn't work for me sadly, GE 37 here, maybe it was the release? 472 installed on 5.0.10 just fine, and yea it took an unreasonable amount of time, then switching to ge37 causes it to false launch (now playing but not actually running)

**Comment by TheKarion** [comment]
Trying to switch proton versions now the game crashes on launch

**Comment by Loico84** [comment]
You can try with GE-Proton-7-20 version. I use it and i haven't any problems.

**Comment by Aragas** [comment]
The issue is really weird and internally I'm not sure what is causing this!
If someone in willing to experiment, I can share builds with partially disabled code that is executed at loading time to try to find the cause!

**Comment by AlpacaRotorvator** [comment]
Huh, I still don't know how that happened, but I'm using Proton GE 7.38 with the latest MCM version from the workshop and my game is actually starting up just fine with it enabled! It's a completely clean prefix, no dotnet installed at all. Can anyone reproduce that?

Like I said, I have no idea what I've done here. After installing 7.38 I deleted my prefix a couple of times trying to fiddle around and install, without success, dotnet472, then today when I decided to run steam from CLI to get some startup logs it simply booted up just fine.

**Comment by Aragas** [comment]
Maybe our compatibility layers were at fault. We used indirectly some game types without guaranteeing that the assemblies they are contained in were properly loaded. I wasn't able to confirm this, because the game always loaded everything we needed. On Windows at least.
Maybe there are some quirks on Linux that stop this behaviour.
Again, pure speculation, but the most notable change on v1.0.0, except the MCM backend refactoring, is the compatibility layer removal. Still waiting for more confirmations first

**Comment by Aragas** [comment]
v5.1.0 might fix the issue, please check it!

**Comment by TheKarion** [comment]
![Screenshot_20221110_181410](https://user-images.githubusercontent.com/64805993/201232615-67e47202-c1c6-47f0-8f20-0caeea477131.png)
Aha it works!! Proton Experimental, no launch options or changes.

**Comment by TheKarion** [comment]
Seems to be that a lot of important mods don't work properly, diplomacy crashes on start, rts camera and rts camera commands crashes when in a battle, land of sika crashes when starting a game, and aggregated income also crashes the game on startup. I believe Diplomacy broke due to the 1.01 patch, but not sure.

**Comment by Aragas** [comment]
Are we talking about Linux still with mod crashes?
I believe this is due to a more strict runtime on linux, maybe a difference in the Win->POSIX layer. But some things are clearly working differently.
